htmx_django/apps/core/urls.py
from django.urls import path

from htmx_django.apps.core.views import views_exemplo1, views_exemplo2, views_exemplo3

app_name = 'core'

urlpatterns = [
    path('click_to_load/', views_exemplo1.example_click_load, name='click_to_load'),
    path('replace/', views_exemplo1.replace_example, name='replace'),
    path('filmes/', views_exemplo2.filme_view, name='filme'),
    path('criar_filme/', views_exemplo2.create_filme, name='create_filme'),
    path('render_update/<int:filme_id>/', views_exemplo2.render_update_filme, name='render_update_filme'),
    path('update/<int:filme_id>/', views_exemplo2.update_filme, name='update_filme'),
    path('delete/<int:filme_id>/', views_exemplo2.delete_filme, name='delete_filme'),
    path('search_filme_view/', views_exemplo3.search_filme_view, name='search_filme_view'),
    path('search_filme/', views_exemplo3.search_filme, name='search_films'),
]

htmx_django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('htmx_django.apps.core.urls')),
]

htmx_django/apps/core/models.py
from django.db import models


class Filme(models.Model):
    nome = models.CharField(max_length=256)
    diretor = models.CharField(max_length=256)
    ano = models.CharField(max_length=30)

    def __str__(self):
        return self.nome

htmx_django/apps/core/views/views_exemplo1.py
import uuid

from random import choice

from django.shortcuts import render


def example_click_load(request):
    return render(request, 'exemplo1/click_to_load.html')


def replace_example(request):
    nomes = ['gabriel', 'arthur', 'nicolas', 'fátima', 'maria', 'ana']
    random_nome = choice(nomes)

    context = {
        'pessoa': [random_nome, f'{random_nome}@test.org', uuid.uuid1()]
    }

    return render(request, 'exemplo1/replace_example.html', context=context)

htmx_django/apps/core/views/views_exemplo2.py
from django.forms import modelform_factory
from django.shortcuts import render

from htmx_django.apps.core.models import Filme


def filme_view(request):
    context = {
        'form': modelform_factory(Filme, fields='__all__'),
        'filmes': Filme.objects.all()
    }
    return render(request, 'exemplo2/filmes.html', context=context)


def create_filme(request):
    if request.POST:
        nome = request.POST.get('nome')
        diretor = request.POST.get('diretor')
        ano = request.POST.get('ano')

        Filme.objects.create(nome=nome, diretor=diretor, ano=ano)

    return render(request, 'exemplo2/filme-list.html', context={'filmes': Filme.objects.all()})


def render_update_filme(request, filme_id):
    filme = Filme.objects.get(id=filme_id)

    form = modelform_factory(Filme, fields='__all__')(instance=filme)

    return render(request, 'exemplo2/filme-update.html', context={'form': form, 'filme': filme})


def update_filme(request, filme_id):
    nome = request.POST.get('nome')
    diretor = request.POST.get('diretor')
    ano = request.POST.get('ano')

    Filme.objects.filter(id=filme_id).update(nome=nome, diretor=diretor, ano=ano)

    return filme_view(request)


def delete_filme(request, filme_id):
    filme = Filme.objects.get(id=filme_id)

    filme.delete()

    return render(request, 'exemplo2/filme-list.html', context={'filmes': Filme.objects.all()})

htmx_django/apps/core/views/views_exemplo3.py
from django.http import HttpResponse
from django.shortcuts import render

from htmx_django.apps.core.models import Filme


def search_filme_view(request):
    return render(request, 'exemplo3/search_filmes_view.html')


def search_filme(request):
    search = request.POST.get('search')

    query = Filme.objects.filter(nome__icontains=search)

    if not query.exists() or search == "":
        return HttpResponse('<h5 class="text-center pt-4">Não foi encontrado nenhum resultado </h5>')

    return render(request, 'exemplo3/result_filmes.html', context={'filmes': query.all()})

templates/base.html
{% load bootstrap5 %}
<!doctype html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Exemplos</title>
    {% bootstrap_css %}
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.3/font/bootstrap-icons.css">
</head>
<body>
{% block content %}
{% endblock %}
{% bootstrap_javascript %}
<script src="https://unpkg.com/htmx.org@1.7.0"></script>
<script>
    document.body.addEventListener('htmx:configRequest', (event) => {
        event.detail.headers['X-CSRFToken'] = '{{ csrf_token }}';
    })
</script>
</body>
</html>

templates/exemplo1/click_to_load.html
{% extends 'base.html' %}


{% block content %}
    <div class="d-flex mx-auto pt-5" style="width: 40%;">
        <table class="table">
            <thead>
            <tr>
                <th scope="col">Nome</th>
                <th scope="col">E-mail</th>
                <th scope="col">ID</th>
            </tr>
            </thead>
            <tbody id="addMe">
            </tbody>
        </table>
    </div>
    <button class="text-center btn btn-primary d-block mx-auto mt-3"
            hx-get="{% url 'core:replace' %}"
            hx-target="#addMe"
            hx-swap="beforeend">
        Adicionar pessoa...
    </button>
{% endblock %}

templates/exemplo1/replace_example.html
<tr>
    {% for dado in pessoa %}
        <td>{{ dado }}</td>
    {% endfor %}
</tr>

templates/exemplo2/filme-list.html
{% load bootstrap5 %}

{% for filme in filmes %}
    <tr>
        <td>{{ filme.nome }}</td>
        <td>{{ filme.diretor }}</td>
        <td>{{ filme.ano }}</td>
        <td>
            <span class="text-info" style="cursor: pointer;"
                  hx-get="{% url 'core:render_update_filme' filme.id %}"
                  hx-target="#filme-form">
                <i class="bi bi-pencil-fill"></i>
            </span>
            <span class="ps-3 text-danger cursor-pointer" style="cursor: pointer;"
                  hx-post="{% url 'core:delete_filme' filme.id %}"
                  hx-target="#filme-list">
                <i class="bi bi-trash-fill"></i>
            </span>
        </td>
    </tr>
{% endfor %}

templates/exemplo2/filme-update.html
{% load bootstrap5 %}

<form hx-post="{% url 'core:update_filme' filme.id %}" hx-target="#content" class="d-flex align-items-center">
    {% csrf_token %}
    {% bootstrap_form form %}
    <button type="submit" class="ms-2 mt-3 btn btn-primary">
        Salvar
    </button>
</form>

templates/exemplo2/filmes.html
{% extends 'base.html' %}

{% load bootstrap5 %}

{% block content %}
    <div id="content">
        <div class="mx-auto pt-5" style="width: 50%;">
            <div id="filme-form">
                <form hx-post="{% url 'core:create_filme' %}" hx-target="#filme-list" class="d-flex align-items-center">
                    {% csrf_token %}
                    {% bootstrap_form form %}
                    <button type="submit" class="ms-2 mt-3 btn btn-primary">
                        Adicionar
                    </button>
                </form>
            </div>
            <div>
                <table class="table mt-5">
                    <thead>
                    <tr>
                        <th scope="col">Nome</th>
                        <th scope="col">Diretor</th>
                        <th scope="col">Ano</th>
                        <th scope="col">Gerenciar</th>
                    </tr>
                    </thead>
                    <tbody id="filme-list">
                    {% include 'exemplo2/filme-list.html' %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock %}

templates/exemplo3/result_filmes.html
<table class="table mt-5">
    <thead>
    <tr>
        <th scope="col">Nome</th>
        <th scope="col">Diretor</th>
        <th scope="col">Ano</th>
    </tr>
    </thead>
    <tbody id="filme-list">
    {% for filme in filmes %}
        <tr>
            <td>{{ filme.nome }}</td>
            <td>{{ filme.diretor }}</td>
            <td>{{ filme.ano }}</td>
        </tr>
    {% endfor %}
    </tbody>
</table>

templates/exemplo3/search_filmes_view.html
{% extends 'base.html' %}

{% block content %}
    <div class="mx-auto pt-5" style="width: 50%;">
        <div class="input-group rounded">
            <input type="search" class="form-control rounded" placeholder="Pesquisar" aria-label="Pesquisar"
                   hx-post="{% url 'core:search_films' %}" hx-target="#filme-list"
                   hx-trigger="keyup changed delay:500ms" name="search"/>
            <div class="input-group-text border-0" id="search-addon">
                <i class="bi bi-search"></i>
            </div>
        </div>
        <div id="filme-list">
        </div>
    </div>
{% endblock %}